language: python
python:
- 3.8.5
install:
  - pip install -r requirements.txt
deploy:  
 provider: heroku  
 app: predict-scholar
 on:    
   branch: master
 api_key:
  secure: $HEROKU_API_KEY
script:
- python PredAlunos.py
